export const localRoute = {
  home: '/',
  blog: '/blog',
  blogDetails1: '/blog-details-1',
  blogDetails2: '/blog-details-2',
  blogDetails3: '/blog-details-3',
  blogDetails4: '/blog-details-4',
  contact: '/contact',
  about: '/about',
  services: '/services',
  findjobs: '/findjobs',
  merchantOnboarding:'/merchant-onboarding',
  backgroundVerification:'/background-verification',
  teleSales:'/tele-sales',
  lastMileDelivery:'/last-mile-delivery',
  customerAcquisition:'/customer-acquisition',
  stockAudits:'/stock-audits',
  geoTagging:'/geo-tagging',
  pickingPacking:'/picking-packing',
  surveyCollection:'/survey-collection',
  productSampling:'/product-sampling',
  influencerMarketing:'/influencer-marketing',
  customerSupport:'/customer-support',
  warehouseService:'/warehouse-service',
  contentModeration:'/content-moderation',
  phlebotomyServices:'/phlebotomy-services',
  privacyPolicy:'/privacy-policy',
  casestudyAmazon: '/casestudy-amazon',
  casestudyZomato: '/casestudy-zomato',
  casestudyRapido: '/casestudy-rapido',
  casestudyPhonepay: '/casestudy-phonepay',
  notFound: '*',
  notFound500: '*',
}
